name: iOS starter workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ios-tests:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Xcode version
        run: xcodebuild -version
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Build and Test
        run: |
          set -o pipefail
          xcodebuild \
            -scheme "Quotables" \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -configuration Debug \
            clean test | xcpretty